//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLogic
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public string SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string SubjectAbbreviation { get; set; }
        public byte Credits { get; set; }
        public string SubjectCategory { get; set; }
    
        public virtual SubjectCategory SubjectCategory1 { get; set; }
    }
}
