//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITWALA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subject()
        {
            this.ElectiveSubjects = new HashSet<ElectiveSubject>();
        }
    
        public string SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string SubjectAbbreviation { get; set; }
        public byte Credits { get; set; }
        public string SubjectCategory { get; set; }
    
        public virtual SubjectCategory SubjectCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElectiveSubject> ElectiveSubjects { get; set; }
    }
}
